### ISSUE TITLE
Wrong documentation for update_user

### ISSUE THREAD

**Issue by jide** [usebasejump/basejump#50]
At https://basejump-site.vercel.app/docs/accounts#update-an-account, the metadata field should be public_metadata.

**Comment by tiniscule** [comment]
You are absolutely right, pushing a fix now.

The response is `metadata` though, just heads up.  Wish I'd caught that before I pushed haha.

**Comment by jide** [comment]
No big deal :)

Also I wonder how private_metadata can be updated, and what's the intended use of it ?

**Comment by tiniscule** [comment]
private_metadata I only access through the service_role user - so there's no public access to it.  I think it's a bit debatable how useful it is, since you could just create private tables that operated the same way.  

I use it to store information and things for accounts that are useful in background jobs/scripts mostly.  For example, I'm storing encrypted openai tokens for customers in it in one use case.

**Comment by jide** [comment]
Interesting ! Thanks for the explanation.
